### ISSUE TITLE
Error: no matching function for call to 'swriteSTL' using make -j after successful compilation

### ISSUE THREAD

**Issue by Sangram-Rout** [wimvanrees/growth_SM2018#1]
Error: no matching function for call to 'swriteSTL' using make -j after successful compilation

**Comment by wimvanrees** [comment]
I don't think there is a `swriteSTL` call in the code on github. Can you tell me what line the compiler gets stuck on?

**Comment by sangram1992** [comment]
I have saved the CMake compilation and make -j log in the [https://docs.google.com/document/d/1kYsCE89su6kjv4poyuzmJygTlMpaatYGR6KZfTWs1YA/edit?usp=sharing](url)

**Comment by Sangram-Rout** [comment]
https://docs.google.com/document/d/1kYsCE89su6kjv4poyuzmJygTlMpaatYGR6KZfTWs1YA/edit?usp=sharing

**Comment by Sangram-Rout** [comment]
I have shared the entire log of the compilation from CMake and make -j

**Comment by wimvanrees** [comment]
Thanks - I haven't compiled this code in a while, perhaps it has become incompatible with newer versions of libigl. I'll take a look over the next couple of days.

**Comment by wimvanrees** [comment]
I pushed a commit just now (93e212a6d5f5eb932298fc64827c4416e3ae0b61) - it fixes the compilation error on my machine. Please let me know if it works for you.

**Comment by wimvanrees** [comment]
No new comments, so I assume it's fixed and will close the issue.

**Comment by Sangram-Rout** [comment]
Thank you, Prof. Van Rees. The compilation works now.
